name: app_login
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  flutter_local_notifications: ^21.0.0
  flutter_timezone: ^5.0.2
  timezone: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10


flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/status/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter_native_splash:
  color: "#2196F3" 
  image: assets/logo.png

  android_12:
    image: assets/logo.png
    icon_background_color: "#2196F3"

  android: true
  ios: true