name: app_login
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

# 🔥 CONFIG DO FLUTTER (SÓ UM!)
flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

# 🔥 ÍCONE DO APP
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

# 🔥 SPLASH NATIVA (PRIMEIRA TELA)
flutter_native_splash:
  color: "#2196F3" # mesma cor da sua splash
  image: assets/logo.png

  android_12:
    image: assets/logo.png
    icon_background_color: "#2196F3"

  android: true
  ios: true