// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpjNlrb3aoz0UAYsx-GsAN-Mo8u4JKptA',
    appId: '1:637144740072:web:534fa60da2f60c23a2d95d',
    messagingSenderId: '637144740072',
    projectId: 'barbearia-33ef7',
    authDomain: 'barbearia-33ef7.firebaseapp.com',
    storageBucket: 'barbearia-33ef7.firebasestorage.app',
    measurementId: 'G-YQKD51C74M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG6RTW3Ch4jU9YVSX3XRQ_r7lcP-bRIS0',
    appId: '1:637144740072:android:c8c3b6d3801fddf7a2d95d',
    messagingSenderId: '637144740072',
    projectId: 'barbearia-33ef7',
    storageBucket: 'barbearia-33ef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuK0vPizzhkV58DWEO7ZKkSit30KsuRmM',
    appId: '1:637144740072:ios:61db030e34659ab3a2d95d',
    messagingSenderId: '637144740072',
    projectId: 'barbearia-33ef7',
    storageBucket: 'barbearia-33ef7.firebasestorage.app',
    iosClientId: '637144740072-occeovt1fhuvvnchrbpijmc0l1hohfra.apps.googleusercontent.com',
    iosBundleId: 'com.example.appLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuK0vPizzhkV58DWEO7ZKkSit30KsuRmM',
    appId: '1:637144740072:ios:61db030e34659ab3a2d95d',
    messagingSenderId: '637144740072',
    projectId: 'barbearia-33ef7',
    storageBucket: 'barbearia-33ef7.firebasestorage.app',
    iosClientId: '637144740072-occeovt1fhuvvnchrbpijmc0l1hohfra.apps.googleusercontent.com',
    iosBundleId: 'com.example.appLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpjNlrb3aoz0UAYsx-GsAN-Mo8u4JKptA',
    appId: '1:637144740072:web:7b8a0cc87aec62a8a2d95d',
    messagingSenderId: '637144740072',
    projectId: 'barbearia-33ef7',
    authDomain: 'barbearia-33ef7.firebaseapp.com',
    storageBucket: 'barbearia-33ef7.firebasestorage.app',
    measurementId: 'G-R136ZJJR2V',
  );

}